name: Output Event Details
on: issues
jobs:
  event_details:
    runs-on: ubuntu-latest
    steps:
      - name: event-name
        run: echo "${{ toJSON(github.event_name) }}"
      - name: event-details
        run: echo "${{ toJSON(github.event) }}"
